### ISSUE TITLE
Backwards compatibility with Version 1.3.1post1

### ISSUE THREAD

**Issue by tonggehua** [imr-framework/pypulseq#69]
**Describe the bug**
Version 1.4.0 (commit 5ef964c5bb0515260aac9acc760ee385f7c38fa1) cannot read seq files generated with Version 1.3.1post1

**To Reproduce**
1. Pull from referenced commit
2. Run the following in Python console:
``` 
from pypulseq.Sequence.sequence import Sequence
seq =  Sequence()
seq.read('ute2d.seq')
```
**(This leads to Error 1)** 
3. Change the version number in the seq file from 1.3.1post1 to 1.3.1 and rerun the same thing 
**(This leads to Error 2)** 

**Error 1:** 
Traceback (most recent call last):
  File "C:\Users\tongg\PycharmProjects\disimpy\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-d166ab9c62c3>", line 1, in <module>
    seq.read('ute2d.seq')
  File "C:\Users\tongg\PycharmProjects\pypulseq\pypulseq\Sequence\sequence.py", line 943, in read
    read(self, path=file_path, detect_rf_use=detect_rf_use)
  File "C:\Users\tongg\PycharmProjects\pypulseq\pypulseq\Sequence\read_seq.py", line 98, in read
    version_major, version_minor, version_revision = __read_version(input_file)
  File "C:\Users\tongg\PycharmProjects\pypulseq\pypulseq\Sequence\read_seq.py", line 412, in __read_version
    revision = int(tok[1])
ValueError: invalid literal for int() with base 10: '1post1'

**Error 2:** 
Traceback (most recent call last):
  File "C:\Users\tongg\PycharmProjects\disimpy\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-d166ab9c62c3>", line 1, in <module>
    seq.read('ute2d.seq')
  File "C:\Users\tongg\PycharmProjects\pypulseq\pypulseq\Sequence\sequence.py", line 943, in read
    read(self, path=file_path, detect_rf_use=detect_rf_use)
  File "C:\Users\tongg\PycharmProjects\pypulseq\pypulseq\Sequence\read_seq.py", line 225, in read
    self.rf_library.data[i][:3],
KeyError: 0

**Expected behavior**
The sequence should be loaded without generating either error. 

**Desktop (please complete the following information):**
 - OS: Windows 10 
- `pypulseq` version: 1.4.0 (5ef964c5bb0515260aac9acc760ee385f7c38fa1)

**Seq file used**
`ute2d.seq` (Attached; change extension to .seq before using)
[ute2d.md](https://github.com/imr-framework/pypulseq/files/8950087/ute2d.md)

**Comment by schuenke** [comment]
I am struggling with the same problem. Are you working on a solution yet or should I try finding a solution and create a PR? Don't wanna spend time on it if you are almost done anyway.

**Comment by sravan953** [comment]
@schuenke I have not yet started working on it - but I will get it done soon. Thanks for offering to help!

**Comment by schuenke** [comment]
@sravan953 it seems to work for me. Thanks 👍
